export class PermissionCodeConst {
  public static PERMISSION_SYSTEM = 'PERMISSION_SYSTEM';
  public static PERMISSION_ACCOUNT = 'PERMISSION_ACCOUNT';
  public static PERMISSION_ACCOUNT_ADD = 'PERMISSION_ACCOUNT_ADD';
  public static PERMISSION_ROLE = 'PERMISSION_ROLE';
  public static PERMISSION_PERMISSION = 'PERMISSION_PERMISSION';

  public static PERMISSION_ORDER = 'PERMISSION_ORDER';
  public static PERMISSION_SUPPORT = 'PERMISSION_SUPPORT';
}
